"""Add new columns

Revision ID: 73feaf7aa17a
Revises: 
Create Date: 2024-03-31 11:52:19.176510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73feaf7aa17a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image_files',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('image_files',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
